export const slideData = [
    './../../assets/images/slide1.jpg',
    './../../assets/images/slide2.jpg',
    './../../assets/images/slide3.jpg',
    './../../assets/images/slide4.jpg',
    './../../assets/images/slide5.jpg',
    './../../assets/images/slide6.jpg',
    './../../assets/images/slide7.jpg',
    './../../assets/images/slide8.jpg',
    './../../assets/images/slide9.jpg',
    './../../assets/images/slide10.jpg',
    './../../assets/images/slide11.jpg',
    './../../assets/images/slide12.jpg',
    './../../assets/images/slide13.jpg',
    './../../assets/images/slide14.jpg',
    './../../assets/images/slide15.jpg',
    './../../assets/images/slide16.jpg',
]
